// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoqgnlrjknuhrqbscafd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvcWdubHJqa251aHJxYnNjYWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDM0MTEsImV4cCI6MjA2NDExOTQxMX0.UmiE5aWArXQG15cxPfhIp954EIdcuMdtyGe1PA2P-Jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);